version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build_and_test: build and test
    docker:
      - image: cimg/python:3.12.0

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
          pip-dependency-file: requirements.txt
      - run:
          name: check test with Pytest
          command: pytest --nomigrations --disable-warnings

  flake8:
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - run:
          name: Install Flake8
          command: pip install flake8==3.7.0
      - run:
          name: check linting with Flake8
          command: flake8

  build-push-docker:
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command:
            docker build -t $DOCKER_IMAGE:latest .
      - run:
          name: Connect to Docker Hub
          command:
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER_ID" --password-stdin
      - run:
          name: Push docker image
          command:
            docker tag $DOCKER_IMAGE $DOCKER_IMAGE |
            docker push $DOCKER_IMAGE

  deploy-from-dockerhub-to-render:
    docker:
      - image: curlimages/curl:latest
    steps:
      - run:
          name: Deploy docker hub image to Render
          command: curl $DEPLOY_HOOK

workflows:
  run_tests_and_build_docker:
    jobs:
      - flake8
      - build-push-docker:
          filters:
            branches:
              only: master
          requires:
            - flake8
      - deploy-from-dockerhub-to-render:
          filters:
            branches:
              only: master
          requires:
            - build-push-docker